<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:arg name="namespace" default="" />

  <xacro:property name="M_PI" value="3.14159"/>

  <xacro:macro name="a200" params="control:='diff_fwd' front_wheels:='outdoor' rear_wheels:='outdoor'">

    <!-- Base Size -->
    <xacro:property name="base_x_size" value="0.98740000" />
    <xacro:property name="base_y_size" value="0.57090000" />
    <xacro:property name="base_z_size" value="0.24750000" />

    <!-- Wheel Mounting Positions -->
    <xacro:property name="wheel_base" value="0.5120" />
    <xacro:property name="wheel_track" value="0.555" />
    <xacro:property name="wheel_vertical_offset" value="0.03282" />

    <!-- Base link is the center of the robot's bottom plate -->
    <link name="base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://warebot/meshes/a200/base_link.dae" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 ${base_z_size/4}" rpy="0 0 0" />
        <geometry>
          <box size="${base_x_size} ${base_y_size} ${base_z_size/2}"/>
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 ${base_z_size*3/4-0.01}" rpy="0 0 0" />
        <geometry>
          <box size="${base_x_size*4/5} ${base_y_size} ${base_z_size/2-0.02}"/>
        </geometry>
      </collision>
    </link>

    <!-- Spawn A200 chassis -->
    <link name="top_chassis_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://warebot/meshes/a200/top_chassis.dae" />
        </geometry>
      </visual>
    </link>

    <!-- Attach chassis to the robot -->
    <joint name="top_chassis_joint" type="fixed">
      <parent link="base_link" />
      <child link="top_chassis_link" />
    </joint>

    <!-- Inertial link stores the robot's inertial information -->
    <link name="inertial_link">
      <inertial>
        <mass value="46.034" />
        <origin xyz="-0.00065 -0.085 0.062" />
        <inertia ixx="0.6022" ixy="-0.02364" ixz="-0.1197" iyy="1.7386" iyz="-0.001544" izz="2.0296" />
      </inertial>
    </link>

    <joint name="inertial_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="inertial_link" />
    </joint>

    <!-- Add wheels -->
    <xacro:include filename="$(find warebot)/description/a200/drivetrain/wheels.urdf.xacro"/>
    <xacro:a200_drivetrain_wheels front_wheels="${front_wheels}" rear_wheels="${rear_wheels}"/>

    <!-- ROS2 Control will be configured separately -->

    <!-- Front bumper mount -->
    <link name="front_bumper_mount"/>

    <joint name="front_bumper_mount_joint" type="fixed">
      <origin xyz="0.406 0 0.091" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="front_bumper_mount" />
    </joint>

    <!-- Rear bumper mount -->
    <link name="rear_bumper_mount"/>

    <joint name="rear_bumper_mount_joint" type="fixed">
      <origin xyz="-0.406 0 0.091" rpy="0 0 ${M_PI}" />
      <parent link="base_link" />
      <child link="rear_bumper_mount" />
    </joint>

    <!-- Default mount -->
    <link name="default_mount"/>

    <joint name="default_mount_joint" type="fixed">
      <child link="default_mount"/>
      <parent link="base_link"/>
      <origin xyz="0.0 0.0 0.224"/>
    </joint>

    <!-- Base footprint is on the ground under the robot -->
    <link name="base_footprint"/>

    <joint name="base_footprint_joint" type="fixed">
      <origin xyz="0 0 ${wheel_vertical_offset - front_wheel_radius}" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="base_footprint" />
    </joint>

  </xacro:macro>

</robot>
